### ISSUE TITLE
Version Control and Code Review Processes

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/report-sscrap#12]
- Related #11 
- Use version control (like Git) effectively for tracking changes and collaboration.
- Implement code review practices to maintain code quality and adherence to standards.

**Comment by Tekum-Emmanuella** [comment]
Good morning sir please i want this ticket.
 Thank you!

**Comment by Tekum-Emmanuella** [comment]
No please don't assign me to it i please
