### ISSUE TITLE
Implement Error Handling Mechanisms

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/report-sscrap#20]
- Related #10
- Develop error handling logic for each identified potential error source.
- Ensure errors are caught and handled gracefully without causing system crashes.

**Comment by Tekum-Emmanuella** [comment]
Good day sir 
 please i need more feedback on this ticket.
 Am i supposed to include the mechanism for both front-end, back-end?

**Comment by stephane-segning** [comment]
Hello @Tekum-Emmanuella. I explained this yesterday to @ValantineSuh. Ask him for advice. But to put it simply, this is to go through the code and see where error `can` come from, then handle it

**Comment by Tekum-Emmanuella** [comment]
sir  @stephane-segning i think Betrand is the one to do that what i have to do is catch the errors that is ticket #20.
I am so use the try and except method to catch the identified errors

**Comment by stephane-segning** [comment]
Then do it @Tekum-Emmanuella
