### ISSUE TITLE
Integrate Analysis Script with Backend API

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/report-sscrap#39]
- Related #5
- Dependency #38, #34 
- Develop an API endpoint that triggers these analysis scripts.
- Ensure secure and efficient communication between the frontend and the script.

**Comment by Bansikah** [comment]
Devopers: @nancymuyeh  & @Bansikah  will be working on Integrating Analysis Script with Backend API#39 from user story 5
@stephane-segning
