### ISSUE TITLE
Select and Setup Web Scraping Library

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/report-sscrap#49]
- Related #1
- Choose a suitable web scraping library/framework (e.g., Beautiful Soup, Scrapy).
- Set up the library in the project environment

**Comment by AssahBismarkabah** [comment]
hello @Koufan-De-King  so on the libraries have you seen Beautiful Soup: A Python library for parsing HTML documents?

**Comment by NkwaTambe** [comment]
hello sir @stephane-segning i created a pull request on Choosing a suitable web scraping library/framework
